version: '3'
services:
  gogs:
    container_name: gogs
    image: gogs/gogs:0.12
    ports:
      - ${GOGS_PORT:-3000}:3000
    volumes:
      - ./.data/gogs/data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always

  drone:
    image: drone/drone:2
    container_name: drone
    ports:
      - ${DRONE_SERVER_PORT:-8000}:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.data/drone/:/var/lib/drone
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=${DRONE_SERVER_IP}:${DRONE_SERVER_PORT:-8000}
      - DRONE_DEBUG=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GOGS=true
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_PROVIDER=gogs
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_USER_CREATE=username:${DRONE_ADMIN},admin:true
      - DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
      - DRONE_DATABASE_DRIVER=sqlite3
      - TZ=Asia/Shanghai
    restart: always


networks:
  defaults: 
